<?php
/**
 * @var \Fabfuel\Prophiler\ProfilerInterface $profiler
 */

use Fabfuel\Prophiler\Toolbar\Formatter\BenchmarkFormatter;

?>
<!--
<style>
    <?php /*echo file_get_contents(__DIR__ . '/css/screen.css'); */?>
</style>
-->

<div class="request">

    <div class="toolbar">
        <h1 class="logo"><?php echo $this->title; ?></h1>

        <nav>
            <ul>
                <li>
                    <span class="label color-2"><i class="fa fa-clock-o"></i> <?php echo BenchmarkFormatter::formatDuration($profiler->getDuration()) ?></span>
                </li>
                <li>
                    <span class="label color-3"><i class="fa fa-tasks"></i> <?php echo BenchmarkFormatter::formatMemoryUsage(memory_get_peak_usage()) ?></span>
                </li>
                <li data-target="#prophiler-benchmarks-<?= spl_object_hash($profiler) ?>">
                    <a href="javascript:void(0);"><span class="label color-5"><i class="fa fa-tachometer"></i> Timeline</span></a>
                </li>

                <?php foreach ($aggregators as $aggregator): ?>
                    <li data-target="#prophiler-aggregator-<?= spl_object_hash($aggregator) ?>">
                        <?php if (count($aggregator)): ?>
                            <a href="javascript:void(0);">
                        <?php endif; ?>

                        <span class="label severity-<?= $aggregator->getSeverity() ?>">
                            <?= $aggregator->getIcon() ?> <?= $aggregator->getTitle() ?>
                            <span class="badge"><?= count($aggregator) ?></span>
                        </span>
                        <?php if (count($aggregator)): ?>
                            </a>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>

                <?php if (count(new \Fabfuel\Prophiler\Iterator\ComponentFilteredIterator($profiler, 'Logger')) >= 1): ?>
                    <li data-target="#prophiler-logs-<?= spl_object_hash($profiler) ?>">
                        <a href="javascript:void(0);">
                            <span class="label <?= $alertCount ? 'color-0' : 'color-5' ?>">
                                <i class="fa fa-align-left"></i> Logs
                                <?php if ($alertCount): ?>
                                    <span class="badge"><?= $alertCount ?></span>
                                <?php endif; ?>
                            </span>
                        </a>
                    </li>
                <?php endif; ?>

                <?php foreach ($dataCollectors as $dataCollector): ?>
                    <li data-target="#prophiler-datacollector-<?= md5($dataCollector->getTitle()) ?>">
                        <a href="javascript:void(0);"><span class="label color-5"><?= $dataCollector->getIcon() ?> <?= $dataCollector->getTitle() ?></span></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </nav>
    </div>

    <div id="prophiler-benchmarks-<?= spl_object_hash($profiler) ?>" class="benchmarks">
        <?php $this->partial('partials/benchmarks', ['profiler' => $profiler, 'benchmarks' => $profiler, ]); ?>
    </div>

    <div id="prophiler-logs-<?= spl_object_hash($profiler) ?>" class="logs">
        <?php $this->partial('partials/logs', ['profiler' => $profiler]); ?>
    </div>

    <?php foreach ($dataCollectors as $dataCollector): ?>
        <?php $this->partial('partials/datacollector', ['dataCollector' => $dataCollector]); ?>
    <?php endforeach; ?>

    <?php foreach ($aggregators as $aggregator): ?>
        <?php $this->partial('partials/aggregator', ['profiler' => $profiler, 'aggregator' => $aggregator]); ?>
    <?php endforeach; ?>

</div>

<!--
<link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
<script>
    window.addEventListener("load", function () {
        if (!window.jQuery) {
            var script = document.createElement("script");
            script.src = "//code.jquery.com/jquery-2.1.1.min.js";
            script.type = "text/javascript";
            document.getElementsByTagName("head")[0].appendChild(script);
        }
        $('json').each(function (index, el) {
            el.innerHTML = JSON.stringify(JSON.parse(el.innerHTML), null, '    ');
        });
        $("#prophiler nav li").click(function() { $(this).toggleClass("selected"); });
    });
</script>
-->